const WatchlistActionTypes = {
  ADD_ITEM_TO_WATCHLIST: "ADD_ITEM_TO_WATCHLIST",
  REMOVE_ITEM_FROM_WATCHLIST: "REMOVE_ITEM_FROM_WATCHLIST",
  REMOVE_ALL_ITEMS_FROM_WATCHLIST: "REMOVE_ALL_ITEMS_FROM_WATCHLIST",
};

export default WatchlistActionTypes;
