const MoviesActionType = {
  FETCH_NOW_PLAYING_START: "FETCH_NOW_PLAYING_START",
  FETCH_NOW_PLAYING_SUCCESS: "FETCH_NOW_PLAYING_SUCCESS",
  FETCH_NOW_PLAYING_FAILURE: "FETCH_NOW_PLAYING_FAILURE",
  FETCH_FEATURED_TODAY_START: "FETCH_FEATURED_TODAY_START",
  FETCH_FEATURED_TODAY_SUCCESS: "FETCH_FEATURED_TODAY_SUCCESS",
  FETCH_FEATURED_TODAY_FAILURE: "FETCH_FEATURED_TODAY_FAILURE",
  FETCH_FAN_FAVORITES_START: "FETCH_FAN_FAVORITES_START",
  FETCH_FAN_FAVORITES_SUCCESS: "FETCH_FAN_FAVORITES_SUCCESS",
  FETCH_FAN_FAVORITES_FAILURE: "FETCH_FAN_FAVORITES_FAILURE",
  FETCH_SEARCH_MOVIE_START: "FETCH_SEARCH_MOVIE_START",
  FETCH_SEARCH_MOVIE_SUCCESS: "FETCH_SEARCH_MOVIE_SUCCESS",
  FETCH_SEARCH_MOVIE_FAILURE: "FETCH_SEARCH_MOVIE_FAILURE",
  SEARCH_INPUT: "SEARCH_INPUT",
  CLEAR_SEARCH_ENTRY: "CLEAR_SEARCH_ENTRY",
  CLEAR_SEARCH_COLLECTIONS: "CLEAR_SEARCH_COLLECTIONS",
};

export default MoviesActionType;
