const MoviesActionType = {
  FETCH_NOW_PLAYING_START: "FETCH_NOW_PLAYING_START",
  FETCH_NOW_PLAYING_SUCCESS: "FETCH_NOW_PLAYING_SUCCESS",
  FETCH_NOW_PLAYING_FAILURE: "FETCH_NOW_PLAYING_FAILURE",
  FETCH_FEATURED_TODAY_START: "FETCH_FEATURED_TODAY_START",
  FETCH_FEATURED_TODAY_SUCCESS: "FETCH_FEATURED_TODAY_SUCCESS",
  FETCH_FEATURED_TODAY_FAILURE: "FETCH_FEATURED_TODAY_FAILURE",
};

export default MoviesActionType;
